server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/products {
        proxy_pass http://product-service:3030/products;
    }

    location /api/orders {
        proxy_pass http://order-service:3000/orders;
    }
}